
use master	
go
create database QLKS
go
use QLKS
go


CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10),
	TENKH NVARCHAR(50),
	SOCMND VARCHAR(10),
	DIACHI NVARCHAR(50),
	DIENTHOAI VARCHAR(11),
	QUOCTICH NVARCHAR(50),
	SOHC VARCHAR(10),
	PRIMARY KEY(MAKH)
)

CREATE TABLE PHONG
(
	MAPHONG VARCHAR(10),
	SOPHONG INT,
	LOAIPHONG VARCHAR(5),
	DIENTICH FLOAT,
	TINHTRANG VARCHAR(10),
	DONGIA FLOAT,
	PRIMARY KEY(MAPHONG)
)



CREATE TABLE HOADONDV
(
	MAHDDV VARCHAR(10),
	SOHDDV VARCHAR(10),
	NGAYLAP DATE,
	MAKH VARCHAR(10),
	TENKH NVARCHAR(50),
	SOCMND VARCHAR(10),
	TONGTIEN INT,
	GHICHU NVARCHAR(50),

	PRIMARY KEY(MAHDDV),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON UPDATE CASCADE

)

CREATE TABLE DICHVU
(
	MADV VARCHAR(10),
	TENDV NVARCHAR(50),
	DONGIA FLOAT,
	MOTAKHAC NVARCHAR(50),
	PRIMARY KEY(MADV)
)

CREATE TABLE BOPHAN
(
	MABP VARCHAR(10),
	TENBP NVARCHAR(50),
	MOTA NVARCHAR(50),
	PRIMARY KEY(MABP)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10),
	TENNV NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	DIACHI NVARCHAR(50),
	SODT VARCHAR(11),
	SOCMND VARCHAR(10),
	MABP VARCHAR(10),
	NGAYVAOLAM DATE,
	LUONG FLOAT,
	PRIMARY KEY(MANV),
	FOREIGN KEY (MABP) REFERENCES BOPHAN(MABP) ON UPDATE CASCADE
)
CREATE TABLE PHIEUTHUE
(
	MAPHIEUTHUE VARCHAR(10),
	NGAYLAP DATE,
	MAKH VARCHAR(10),
	SOPHONG INT,
	NGAYDANGKI DATETIME,
	SONGUOI INT,
	NGAYDEN DATETIME,
	NGAYDI DATETIME,
	NVLAP VARCHAR(10),
	PRIMARY KEY(MAPHIEUTHUE),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON UPDATE CASCADE,
	FOREIGN KEY (NVLAP) REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE,
)

CREATE TABLE HOADONTHANHTOAN
(
	MAHD VARCHAR(10),
	MAPHIEUTHUE VARCHAR(10),
	TENKH NVARCHAR(50),
	SOCMND VARCHAR(10),
	TONGTIENDICHVU INT,
	TONGTIENTHANHTOAN INT,
	GHICHU NVARCHAR(50),

	PRIMARY KEY(MAHD),
	FOREIGN KEY (MAPHIEUTHUE) REFERENCES PHIEUTHUE(MAPHIEUTHUE) ON UPDATE CASCADE
)

CREATE TABLE NHACUNGCAP
(
	MANHACC VARCHAR(10),
	TENNHACC NVARCHAR(50),
	SODT VARCHAR(11),
	DIACHI NVARCHAR(50),
	TENNGUOILH NVARCHAR(50),
	THONGTINKHAC NVARCHAR(50),
	PRIMARY KEY(MANHACC)
)

CREATE TABLE TIENNHGI
(
	MATN VARCHAR(10),
	TENTN NVARCHAR(50),
	TINHTRANGTN NVARCHAR(50),
	SOLUONGHIENCO INT,
	PRIMARY KEY(MATN)
)


CREATE TABLE KHO
(
	MAKHO VARCHAR(10),
	TENKHO NVARCHAR(50),
	VITRI NVARCHAR(50),
	MOTA NVARCHAR(50),
	PRIMARY KEY(MAKHO),
	
)
CREATE TABLE HANG
(
	MAHANG VARCHAR(10),
	MAKHO VARCHAR(10),
	TENHANG NVARCHAR(50),
	DONVITINH VARCHAR(10),
	GIA FLOAT,
	SOLUONG INT,
	MOTA NVARCHAR(50),
	PRIMARY KEY(MAHANG),
	FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO) ON UPDATE CASCADE,
	
)
CREATE TABLE GOM
(

MAPHONG VARCHAR(10),
MATN VARCHAR(10),
SOLUONG INT,
PRIMARY KEY(MAPHONG,MATN),
FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) ON UPDATE CASCADE,
FOREIGN KEY (MATN) REFERENCES TIENNHGI(MATN) ON UPDATE CASCADE,

)




CREATE TABLE PHIEUNHAPHANG
(
	MAPHIEUNHAP VARCHAR(10),
	MANHACC VARCHAR(10),
	THOIGIANNHAP DATE,
	NHANVIENNHAP VARCHAR(10),
	TONGSOTIEN FLOAT,
	DSMTCN NVARCHAR(50),
	PRIMARY KEY(MAPHIEUNHAP),
	FOREIGN KEY (NHANVIENNHAP) REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE,
	FOREIGN KEY (MANHACC) REFERENCES NHACUNGCAP(MANHACC) ON UPDATE CASCADE
)

CREATE TABLE PHIEUNHAPDICHVU
(
	MAPHIEUNHAP VARCHAR(10),
	MANHACC VARCHAR(10),
	THOIGIANNHAP DATE,
	NHANVIENNHAP VARCHAR(10),
	TONGSOTIEN FLOAT,
	DSMTCN NVARCHAR(50),
	PRIMARY KEY(MAPHIEUNHAP),
	FOREIGN KEY (MANHACC) REFERENCES NHACUNGCAP(MANHACC) ON UPDATE CASCADE,
	FOREIGN KEY (NHANVIENNHAP) REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE
)

CREATE TABLE PHIEUNHAPTIENNGHI
(
	MAPHIEUNHAP VARCHAR(10),
	MANHACC VARCHAR(10),
	THOIGIANNHAP DATE,
	NHANVIENNHAP VARCHAR(10),
	TONGSOTIEN FLOAT,
	DSMTCN NVARCHAR(50),
	PRIMARY KEY(MAPHIEUNHAP),
	FOREIGN KEY(MANHACC) REFERENCES NHACUNGCAP(MANHACC) ON UPDATE CASCADE,
	FOREIGN KEY ( NHANVIENNHAP) REFERENCES NHANVIEN(MANV) ON UPDATE CASCADE
)
CREATE TABLE CT_HOADONDV
(
	MAHDDV VARCHAR(10),
	MADV VARCHAR(10),
	SOLUONG INT,
	PRIMARY KEY( MAHDDV,MADV),
	FOREIGN KEY (MAHDDV) REFERENCES HOADONDV(MAHDDV) ON UPDATE CASCADE,
	FOREIGN KEY (MADV) REFERENCES DICHVU(MADV) ON UPDATE CASCADE,
	)
	CREATE TABLE CT_PHIEUNHAPDICHVU
	(
	MAPHIEUNHAP VARCHAR(10),
	MADV VARCHAR(10),
	PRIMARY KEY(MAPHIEUNHAP,MADV),
	FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAPDICHVU(MAPHIEUNHAP) ON UPDATE CASCADE,
	FOREIGN KEY (MADV) REFERENCES DICHVU(MADV) ON UPDATE CASCADE
)
	CREATE TABLE  CT_PHIEUNHAPHANG
	(
	MAPHIEUNHAP VARCHAR(10),
	MAHANG VARCHAR(10),
	PRIMARY KEY (MAPHIEUNHAP,MAHANG),
	FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAPHANG(MAPHIEUNHAP) ON UPDATE CASCADE,
	FOREIGN KEY (MAHANG) REFERENCES HANG(MAHANG) ON UPDATE CASCADE

	)
	CREATE TABLE CT_PHIEUNHAPTIENNGHI
	(
	MAPHIEUNHAP VARCHAR(10),
	MATN VARCHAR(10),
	PRIMARY KEY( MAPHIEUNHAP,MATN),
	FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAPTIENNGHI(MAPHIEUNHAP) ON UPDATE CASCADE,
	FOREIGN KEY (MATN) REFERENCES TIENNHGI(MATN) ON UPDATE CASCADE
	)
	CREATE TABLE THUEPHONG
	(
	MAPHIEUTHUE VARCHAR(10),
	MAPHONG VARCHAR(10),
	PRIMARY KEY(MAPHIEUTHUE, MAPHONG),
	FOREIGN KEY (MAPHIEUTHUE) REFERENCES PHIEUTHUE(MAPHIEUTHUE) ON UPDATE CASCADE,
	FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) ON UPDATE CASCADE
	)

